/**
 * Builds src/app/analysis/openingBook.data.ts from the Lichess opening list (CC0 / public domain):
 * https://github.com/lichess-org/chess-openings — clone it and run
 *   npx tsx scripts/build-opening-book.ts <path to chess-openings>
 * Every position reached by a named line becomes a book position; positions where a line ends keep its name.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { Chess } from 'chessops/chess';
import { makeFen } from 'chessops/fen';
import { parseSan } from 'chessops/san';
import { bookKey } from '../src/app/analysis/openingBook.js';

const dir = process.argv[2];
if (!dir) throw new Error('usage: build-opening-book.ts <chess-openings dir>');
const names: string[] = [];
const book = new Map<string, number>(); // key → name index (-1: in book, no name of its own)
for (const f of ['a', 'b', 'c', 'd', 'e']) {
  const rows = readFileSync(join(dir, `${f}.tsv`), 'utf8').trim().split('\n').slice(1);
  for (const row of rows) {
    const [, name, pgn] = row.split('\t');
    const pos = Chess.default();
    let key = '';
    for (const tok of pgn.split(/\s+/)) {
      if (/^\d+\.+$/.test(tok) || tok === '') continue;
      const mv = parseSan(pos, tok);
      if (!mv) throw new Error(`bad move ${tok} in ${name}`);
      pos.play(mv);
      key = bookKey(makeFen(pos.toSetup()));
      if (!book.has(key)) book.set(key, -1);
    }
    let idx = names.indexOf(name);
    if (idx < 0) idx = names.push(name) - 1;
    book.set(key, idx);
  }
}
const entries = [...book.entries()].map(([k, i]) => (i < 0 ? k : `${k}:${i.toString(16)}`));
writeFileSync('src/app/analysis/openingBook.data.ts',
  '/* Generated by scripts/build-opening-book.ts from the Lichess opening list (CC0, public domain). Do not edit. */\n'
  + `export const OPENING_NAMES: string[] = ${JSON.stringify(names)};\n`
  + `export const OPENING_BOOK = ${JSON.stringify(entries.join(','))};\n`);
console.log(`${names.length} names, ${book.size} positions`);
